version: "3.7"
services:
  essetials-builder:
    build:
      context: ./
      dockerfile: Dockerfile.essetials-builder
      args:
        LLVM_VERSION: 11.0.0
        LLD_VERSION: 11.0.0
        CLANG_VERSION: 11.0.0
        ARCH: x86_64
    image: essetials-builder:11.0.0
   
  zig-builder:
     depends_on:
       - essetials-builder
     build:
       context: ./
       dockerfile: Dockerfile.zig-builder
       args:
         ZIG_COMMIT: 783cb980ab137d6a99c20f007d70b4191d4a63c4
     image: zig-builder:0.7.1

  zphinx-builder:
    depends_on:
       - zig-builder
     build:
       context: ./
       dockerfile: Dockerfile.zphinx-builder
       args:
         ZPHINX_COMMIT: b331079
         EQUIHASH_COMMIT: 6884068
     image: zig-builder:0.7.1
      
  zphinx:
    depends_on:
      - zphinx-builder
    build:
      context: ./
      dockerfile: Dockerfile.zphinx
      args:
        LLVM_VERSION: 11.0.0
        LLD_VERSION: 11.0.0
        CLANG_VERSION: 11.0.0
        ARCH: x86_64
        ZIG_COMMIT: 783cb980ab137d6a99c20f007d70b4191d4a63c4
        ZPHINX_COMMIT: b331079
        EQUIHASH_COMMIT: 6884068
    image: zphinx:latest
    ports:
      - 2355:2355
    volumes:
      - ${PWD}/sphinx.cfg:/sphinx.cfg:ro
      - ${PWD}/domain.key:/zphinx-zerver/domain.key:ro
      - ${PWD}/certificate.der:/zphinx-zerver/certificate.der:ro
      - ${PWD}/data:/srv/data:rw
