version: "3.7"
services:
  essetials-builder:
    build:
      context: ./
      dockerfile: Dockerfile.essetials-builder
      args:
        LLVM_VERSION: 13.0.0
        LLD_VERSION: 13.0.0
        CLANG_VERSION: 13.0.0
        ARCH: x86_64
    image: essetials-builder:latest
   
  zig-builder:
     depends_on:
       - essetials-builder
     build:
       context: ./
       dockerfile: Dockerfile.zig-builder
       args:
         ZIG_COMMIT: a18bf7a
     image: zig-builder:latest

  zphinx-builder:
     depends_on:
       - zig-builder
     build:
       context: ./
       dockerfile: Dockerfile.zphinx-builder
       args:
         ZPHINX_COMMIT: c080ede
         EQUIHASH_COMMIT: 6884068
     image: zig-builder:latest
      
  zphinx:
    depends_on:
      - zphinx-builder
    build:
      context: ./
      dockerfile: Dockerfile.zphinx
      args:
        LLVM_VERSION: 13.0.0
        LLD_VERSION: 13.0.0
        CLANG_VERSION: 13.0.0
        ARCH: x86_64
        ZIG_COMMIT: a18bf7a
        ZPHINX_COMMIT: c080ede
        EQUIHASH_COMMIT: 6884068
    image: zphinx-zerver-docker:zphinx-c080ede
    ports:
      - 127.0.0.1:2355:2355
    volumes:
      - ${PWD}/sphinx.cfg:/sphinx.cfg:ro
      - ${PWD}/ssl_cert.pem:/zphinx-zerver/ssl_cert.pem:ro
      - ${PWD}/ssl_key.pem:/zphinx-zerver/ssl_key.pem:ro
      - ${PWD}/data:/srv/data:rw
