version: "3.7"
services:
  zphinx:
    image: zphinx-server-docker:latest
    ports:
      - 2355:2355
    volumes:
      - ${PWD}/sphinx.cfg:/sphinx.cfg:ro
      - ${PWD}/domain.key:/zphinx-zerver/domain.key:ro
      - ${PWD}/certificate.der:/zphinx-zerver/certificate.der:ro
      - ${PWD}/data:/srv/data:rw
