version: "3.7"
services:
  zphinx:
    cap_drop:
      - ALL
    image: zphinx:latest
    #command: ["docker-init"]
    restart: unless-stopped
    ports:
      - 4443:2355
    volumes:
      #- ./keys/:/tmp/keys/:rw
      - ./keys/:/etc/ssl/sphinx/:ro
      - ./sphinx.cfg:/etc/sphinx/config:ro
      - data:/var/lib/sphinx:rw

volumes:
  data: