version: "3.7"
services:
  zphinx:
    cap_drop:
      - ALL
    image: d3vm/zphinx-zerver-docker:zphinx-c080ede
    ports:
      - 443:2355
    volumes:
      - ${PWD}/sphinx.cfg:/sphinx.cfg:ro
      - ${PWD}/ssl_key.pem:/zphinx-zerver/ssl_key.pem:ro
      - ${PWD}/ssl_cert.pem:/zphinx-zerver/ssl_cert.pem:ro
      - ${PWD}/data:/srv/data:rw
